services:
  - type: web
    name: moonhard-remote-v2-server
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: APP_NAME
        value: MoonHard Remote v2 Server
      - key: APP_VERSION
        value: 1.0.0
      - key: ENVIRONMENT
        value: production